// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using emotions_wpf;

#nullable disable

namespace emotionswpf.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221121074835_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("emotions_wpf.Emotion_", b =>
                {
                    b.Property<int>("Emotion_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("value")
                        .HasColumnType("REAL");

                    b.HasKey("Emotion_Id");

                    b.HasIndex("ImageInfoId");

                    b.ToTable("emotions");
                });

            modelBuilder.Entity("emotions_wpf.ImageInfo", b =>
                {
                    b.Property<int>("ImageInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("hash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImageInfoId");

                    b.ToTable("images");
                });

            modelBuilder.Entity("emotions_wpf.ImageValue", b =>
                {
                    b.Property<int>("ImageInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ImageInfoId");

                    b.ToTable("values");
                });

            modelBuilder.Entity("emotions_wpf.Emotion_", b =>
                {
                    b.HasOne("emotions_wpf.ImageInfo", "image")
                        .WithMany("emotions")
                        .HasForeignKey("ImageInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("image");
                });

            modelBuilder.Entity("emotions_wpf.ImageValue", b =>
                {
                    b.HasOne("emotions_wpf.ImageInfo", "image")
                        .WithOne("value")
                        .HasForeignKey("emotions_wpf.ImageValue", "ImageInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("image");
                });

            modelBuilder.Entity("emotions_wpf.ImageInfo", b =>
                {
                    b.Navigation("emotions");

                    b.Navigation("value")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
